"""empty message

Revision ID: 498fb16ea36a
Revises: 6831ad656e32
Create Date: 2021-07-04 01:45:46.805445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498fb16ea36a'
down_revision = '6831ad656e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
