"""empty message

Revision ID: b37966c34573
Revises: 5f3eb7e1b106
Create Date: 2021-07-04 18:32:26.344138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37966c34573'
down_revision = '5f3eb7e1b106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'looking_for_venues',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('venues', 'looking_for_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'looking_for_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('artists', 'looking_for_venues',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
