"""empty message

Revision ID: c7405f32988e
Revises: 8d6b39bee75a
Create Date: 2021-07-04 03:26:03.199039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7405f32988e'
down_revision = '8d6b39bee75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venues', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venues', 'cities', ['city_id'], ['id'])
    op.drop_column('venues', 'city')
    op.drop_column('venues', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('venues', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'city_id')
    op.drop_table('cities')
    # ### end Alembic commands ###
